export const EXERCISE_DB = [
  { name:"DC HALTÈRE", category:"chest", equipment:"haltères",
    musclesFront:["chest","triceps"], musclesBack:["triceps"],
    tips:["Rétracte les omoplates avant de saisir les haltères.","Descends en 3 temps, coudes à 45°.","Cherche l'étirement maximal des pectoraux en bas."],
    sets:3, repRange:[6,10] },
  { name:"DI HALTÈRE", category:"chest", equipment:"haltères",
    musclesFront:["chest","deltoids"], musclesBack:[],
    tips:["Banc incliné 30-45° max.","Trajectoire légèrement convergente en haut.","Contrôle la descente."],
    sets:3, repRange:[8,12] },
  { name:"ÉCARTÉ POULIE", category:"chest", equipment:"poulie",
    musclesFront:["chest","deltoids"], musclesBack:[],
    tips:["Mouvement en arc — embrasse un arbre.","Léger fléchi permanent des coudes.","Ralentis la descente."],
    sets:3, repRange:[10,15] },
  { name:"ÉCARTÉ HALTÈRE", category:"chest", equipment:"haltères",
    musclesFront:["chest"], musclesBack:[],
    tips:["Amplitude maximale en bas.","Pince les pectoraux en haut.","Charge légère — l'étirement prime."],
    sets:3, repRange:[10,15] },
  { name:"DÉVELOPPÉ MILITAIRE", category:"shoulders", equipment:"haltères",
    musclesFront:["deltoids","triceps"], musclesBack:["trapezius"],
    tips:["Coudes légèrement devant le buste.","Verrouillage en haut sans claquer.","Core engagé tout au long."],
    sets:3, repRange:[8,12] },
  { name:"ÉLÉVATION LATÉRALE", category:"shoulders", equipment:"haltères",
    musclesFront:["deltoids"], musclesBack:["deltoids"],
    tips:["Légère inclinaison avant du buste.","Monte jusqu'à l'horizontale max.","Descente lente 3 secondes."],
    sets:3, repRange:[12,15] },
  { name:"ÉLÉVATION FRONTALE", category:"shoulders", equipment:"haltères",
    musclesFront:["deltoids"], musclesBack:[],
    tips:["Pouce légèrement vers le haut.","Ne dépasse pas l'horizontale.","Alterner ou simultané."],
    sets:3, repRange:[12,15] },
  { name:"OISEAU", category:"shoulders", equipment:"haltères",
    musclesFront:[], musclesBack:["deltoids","upper-back"],
    tips:["Buste parallèle au sol.","Coudes légèrement fléchis, fixes.","Pince les omoplates en haut."],
    sets:3, repRange:[12,15] },
  { name:"TIRAGE MENTON", category:"shoulders", equipment:"poulie",
    musclesFront:["deltoids","biceps"], musclesBack:["trapezius"],
    tips:["1er temps : coudes épaules. 2e : mains au menton.","Coudes toujours au-dessus des mains.","Lent et contrôlé."],
    sets:3, repRange:[8,12] },
  { name:"CURL MARTEAU POULIE", category:"biceps", equipment:"poulie",
    musclesFront:["biceps","forearm"], musclesBack:[],
    tips:["Coudes fixes contre le corps.","Poignet neutre tout au long.","Descente 3-4 secondes."],
    sets:3, repRange:[8,12] },
  { name:"CURL INCLINÉ HALTÈRE", category:"biceps", equipment:"haltères",
    musclesFront:["biceps"], musclesBack:[],
    tips:["Banc incliné : étirement maximal en bas.","Coudes fixes, ne les avance pas.","Enchaîne directement."],
    sets:3, repRange:[8,12] },
  { name:"CURL BARRE EZ", category:"biceps", equipment:"barre",
    musclesFront:["biceps","forearm"], musclesBack:[],
    tips:["Prise supinée légèrement plus large que les épaules.","Coudes absolument fixes.","Ne balance pas le dos."],
    sets:3, repRange:[8,12] },
  { name:"CURL CONCENTRÉ", category:"biceps", equipment:"haltères",
    musclesFront:["biceps"], musclesBack:[],
    tips:["Coude contre la face interne de la cuisse.","Montée complète, contraction maximale.","Descente contrôlée."],
    sets:3, repRange:[10,14] },
  { name:"EXTENSION POULIE HAUTE", category:"triceps", equipment:"poulie",
    musclesFront:["triceps"], musclesBack:["triceps"],
    tips:["Coudes fixes, légèrement devant les oreilles.","Contraction parfaite en extension complète.","Descente contrôlée en 3 secondes."],
    sets:3, repRange:[8,12] },
  { name:"EXTENSION POULIE BASSE", category:"triceps", equipment:"poulie",
    musclesFront:["triceps"], musclesBack:["triceps"],
    tips:["Corde derrière la tête : étirement maximal du triceps long.","Coudes collés aux tempes, fixes tout au long.","Extension totale des bras en haut."],
    sets:3, repRange:[8,12] },
  { name:"DIPS", category:"triceps", equipment:"poids du corps",
    musclesFront:["chest","triceps"], musclesBack:["triceps"],
    tips:["Corps légèrement penché en avant pour les pectoraux.","Descente contrôlée jusqu'aux coudes à 90°.","Extension complète en haut."],
    sets:3, repRange:[8,12] },
  { name:"KICKBACK", category:"triceps", equipment:"haltères",
    musclesFront:[], musclesBack:["triceps"],
    tips:["Buste parallèle au sol, bras plaqué contre le corps.","Extension complète du coude en arrière.","Contraction maximale en fin de course."],
    sets:3, repRange:[12,15] },
  { name:"TIRAGE VERTICAL", category:"back", equipment:"machine",
    musclesFront:["biceps"], musclesBack:["upper-back","trapezius"],
    tips:["Prise légèrement plus large que les épaules.","Tire vers le haut de la poitrine.","Pense 'coudes vers les hanches'."],
    sets:3, repRange:[6,10] },
  { name:"TIRAGE HORIZONTAL", category:"back", equipment:"poulie",
    musclesFront:["biceps"], musclesBack:["upper-back","lower-back"],
    tips:["Torse droit, légèrement penché en avant.","Ramène les coudes derrière le buste.","Rétracte les omoplates — tiens 1 seconde."],
    sets:3, repRange:[8,12] },
  { name:"ROWING BARRE", category:"back", equipment:"barre",
    musclesFront:["biceps"], musclesBack:["upper-back","lower-back","trapezius"],
    tips:["Buste à 30-45° de l'horizontale.","Tire vers le bas du sternum.","Rétracte les omoplates à chaque rep."],
    sets:3, repRange:[8,10] },
  { name:"SOULEVÉ DE TERRE", category:"back", equipment:"barre",
    musclesFront:["quadriceps"], musclesBack:["lower-back","gluteal","hamstring","trapezius"],
    tips:["Barre collée aux tibias.","Dos droit, scapulas engagées.","Extension complète des hanches en haut."],
    sets:4, repRange:[4,6] },
  { name:"SQUAT", category:"legs", equipment:"barre",
    musclesFront:["quadriceps","adductors"], musclesBack:["gluteal","hamstring","lower-back"],
    tips:["Pieds largeur épaules, pointes légèrement ouvertes.","Descente profonde, cuisses parallèles minimum.","Genoux dans l'axe des pointes."],
    sets:4, repRange:[5,8] },
  { name:"HACK SQUAT", category:"legs", equipment:"machine",
    musclesFront:["quadriceps"], musclesBack:["gluteal","hamstring"],
    tips:["Pieds hauts = fessiers/ischio | Pieds bas = quadriceps.","Montée en gamme, échec sur la 3e série.","Alterne : 3 reps charge max ou 5 reps volume."],
    sets:3, repRange:[3,5] },
  { name:"PRESSE À CUISSES", category:"legs", equipment:"machine",
    musclesFront:["quadriceps","adductors"], musclesBack:["gluteal"],
    tips:["Pieds hauts = fessiers/ischio.","Ne verrouille jamais les genoux en haut.","Amplitude complète."],
    sets:3, repRange:[8,12] },
  { name:"LEG CURL", category:"legs", equipment:"machine",
    musclesFront:[], musclesBack:["hamstring","calves"],
    tips:["Pointe les orteils vers toi.","Contraction maximale, descente 3 secondes.","Dégressive possible."],
    sets:3, repRange:[8,12] },
  { name:"LEG EXTENSION", category:"legs", equipment:"machine",
    musclesFront:["quadriceps"], musclesBack:[],
    tips:["Contraction électrique en haut — tiens 2 secondes.","Dégressive : à l'échec puis -20-25%.","Pied neutre / tourné en variation."],
    sets:3, repRange:[8,12] },
  { name:"FENTES", category:"legs", equipment:"haltères",
    musclesFront:["quadriceps","adductors"], musclesBack:["gluteal","hamstring"],
    tips:["Genou avant jamais devant la pointe du pied.","Descente contrôlée, pousse sur le talon avant.","Corps droit, pas d'inclinaison."],
    sets:3, repRange:[10,12] },
  { name:"HIP THRUST", category:"legs", equipment:"barre",
    musclesFront:[], musclesBack:["gluteal","hamstring"],
    tips:["Dos appuyé sur banc à hauteur des omoplates.","Extension complète des hanches en haut.","Contraction 1 seconde au sommet."],
    sets:3, repRange:[10,15] },
  { name:"MOLLETS DEBOUT", category:"legs", equipment:"machine",
    musclesFront:["calves","tibialis"], musclesBack:["calves"],
    tips:["Pause 2 secondes en bas — étirement complet.","Monte le plus haut possible, tiens 1 seconde.","Mouvement lent — le mollet répond au temps sous tension."],
    sets:4, repRange:[12,15] },
  { name:"CRUNCH", category:"abs", equipment:"poids du corps",
    musclesFront:["abs"], musclesBack:[],
    tips:["Mains derrière la nuque, coudes ouverts.","Exhale en montant, inspire en descendant.","Contraction maximale en haut."],
    sets:3, repRange:[15,20] },
  { name:"GAINAGE", category:"abs", equipment:"poids du corps",
    musclesFront:["abs","obliques"], musclesBack:["lower-back"],
    tips:["Ligne droite de la tête aux talons.","Core contracté, respiration régulière.","Progresser en durée chaque semaine."],
    sets:3, repRange:[30,60] },
];

export const CATEGORIES = [
  { id:"all",       label:"TOUT" },
  { id:"chest",     label:"PECS" },
  { id:"shoulders", label:"ÉPAULES" },
  { id:"biceps",    label:"BICEPS" },
  { id:"triceps",   label:"TRICEPS" },
  { id:"back",      label:"DOS" },
  { id:"legs",      label:"JAMBES" },
  { id:"abs",       label:"ABS" },
];
